# Generated by Django 5.0.7 on 2025-01-01 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='addresses',
        ),
    ]
