# Generated by Django 5.0.7 on 2025-01-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_remove_account_addresses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
