# Generated by Django 5.0.7 on 2025-01-04 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='Comment.comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='isVerified',
            field=models.BooleanField(default=True),
        ),
    ]
