# Generated by Django 5.0.7 on 2025-01-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0002_comment_parent_alter_comment_isverified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
