# Generated by Django 5.0.7 on 2025-01-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0003_remove_comment_title_alter_comment_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_for',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
