# Generated by Django 5.0.7 on 2025-03-15 21:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0002_alter_food_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10000000)]),
        ),
    ]
