# Generated by Django 5.0.7 on 2025-03-17 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0003_alter_food_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='price',
        ),
    ]
