# Generated by Django 5.0.7 on 2025-04-20 12:51

import Utils.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0004_remove_food_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizemodel',
            name='uuid',
            field=models.CharField(default=Utils.functions.get_uuid, editable=False, max_length=15, unique=True),
        ),
    ]
