# Generated by Django 5.0.7 on 2025-01-05 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0002_remove_restaurant_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='brief_address',
        ),
    ]
