# Generated by Django 5.0.7 on 2025-02-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0003_remove_restaurant_brief_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='coverage',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
