# Generated by Django 5.0.7 on 2025-02-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0006_alter_restaurant_coverage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='coverage',
            field=models.JSONField(default=list),
        ),
    ]
