# Generated by Django 5.0.7 on 2025-04-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0002_remove_ordermodel_total_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmodel',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
