# Generated by Django 5.0.7 on 2025-04-12 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0003_transactionmodel_accepted_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionmodel',
            old_name='status_changed_at',
            new_name='changed_at',
        ),
        migrations.RemoveField(
            model_name='transactionmodel',
            name='accepted_at',
        ),
        migrations.RemoveField(
            model_name='transactionmodel',
            name='brief_address',
        ),
        migrations.RemoveField(
            model_name='transactionmodel',
            name='client_phone',
        ),
        migrations.RemoveField(
            model_name='transactionmodel',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='transactionmodel',
            name='longitude',
        ),
    ]
