# Generated by Django 5.0.7 on 2025-04-12 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Address', '0003_remove_address_created_by_address_owner_account'),
        ('Transaction', '0004_rename_status_changed_at_transactionmodel_changed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmodel',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Address.address'),
        ),
    ]
