name: Flutter CI

on:
  push:
    branches:
      - main # Or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 # Checks out your repository

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0' # Specify your desired Flutter version

      - name: Install dependencies
        run: flutter pub get
        working-directory: mobile

      - name: Analyze project
        run: flutter analyze
        working-directory: mobile

      - name: Build APK # Or 'flutter build ios' for iOS
        run: flutter build apk
        working-directory: mobile
        # Optional: Add artifact uploading here if you want to store the build